name: CI

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ci:
    uses: crashoutcompany/.github/.github/workflows/ci.yml@v1
    with:
      has-e2e: false
    secrets: inherit
